package Paintdib;

import Sonido.Soundclick;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kira
 */
public class GarciPaintXD extends javax.swing.JFrame implements ActionListener, KeyListener {

    JFileChooser archivos = new JFileChooser();
    private Renderizado r;
    JPanel pnlCurva, pnlImg;
    JButton jb1, jb2, jb3;
    JLabel jl1, jl2, jl3;
    JTextField jt1, jt2;
    String cancionReal;
    boolean sonando = false, pausado = false, detenido = false;
    private String ximg;

    public GarciPaintXD() {
        initComponents();
        setLocationRelativeTo(null);//Coloca el frame en el centro de la pantalla
        setResizable(false);//Deshabilita maximizar
        setLayout(null);
        addKeyListener(this);
        setFocusable(true);
        txtfRelleno.setEditable(false);
        txtfBorde.setEditable(false);

        flowJP();
        gridJP();
        pnlImg.setBounds(700, 20, 251, 93);
        add(pnlImg);
        pnlCurva.setBounds(700, 20, 251, 93);
        add(pnlCurva);

        Panel_principal o = new Panel_principal();
        this.add(o, BorderLayout.CENTER);

        r = new Renderizado(Lienzo.getWidth(), Lienzo.getHeight());
        Lienzo.add(r);
        Lienzo.setBackground(Color.WHITE);
        //addKeyListener(new Teclado(this,r));
        txtfBorde.setEditable(false);
        txtfRelleno.setEditable(false);

        txtfBorde.setBackground(Color.BLACK);

        //Implemetacion del sonido
        new Soundclick(btnLapiz);
        new Soundclick(btnLinea);
        new Soundclick(btnRectangulo);
        new Soundclick(btnCirculo);
        new Soundclick(btnTriangulo);
        new Soundclick(btnCurva);
        new Soundclick(btnCirculoRelleno);
        new Soundclick(btnTrianguloRelleno);
        new Soundclick(btnRectanguloRelleno);
        new Soundclick(btnGoma);
        new Soundclick(btnPincel);
        new Soundclick(btnPunto);
        new Soundclick(btnCirculoSombra);
        new Soundclick(btnRectanguloSombra);
        
        /*estos no suenan por el evento que tiene
        *new Soundclick(btnTexto);
        *new Soundclick(btnImagen);
        *new Soundclick(btnFondo);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lienzo = new javax.swing.JPanel();
        txtfBorde = new javax.swing.JTextField();
        Contornorgb = new javax.swing.JButton();
        Relleno = new javax.swing.JButton();
        txtfRelleno = new javax.swing.JTextField();
        btnFondo = new javax.swing.JButton();
        btnImagen = new javax.swing.JButton();
        btnCurva = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        btnRectangulo = new javax.swing.JButton();
        btnLinea = new javax.swing.JButton();
        btnLapiz = new javax.swing.JButton();
        btnCirculoRelleno = new javax.swing.JButton();
        btnRectanguloRelleno = new javax.swing.JButton();
        btnTrianguloRelleno = new javax.swing.JButton();
        btnTexto = new javax.swing.JButton();
        btnPincel = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnGoma = new javax.swing.JButton();
        btnCirculoSombra = new javax.swing.JButton();
        btnRectanguloSombra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Guardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        limpiar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Translado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemDeshacer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GarciPaint V1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        setIconImage(getIconImage());
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lienzo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area Dibujo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        Lienzo.setAutoscrolls(true);
        Lienzo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout LienzoLayout = new javax.swing.GroupLayout(Lienzo);
        Lienzo.setLayout(LienzoLayout);
        LienzoLayout.setHorizontalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        LienzoLayout.setVerticalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        getContentPane().add(Lienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, 910, 410));

        txtfBorde.setEditable(false);
        txtfBorde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfBordeActionPerformed(evt);
            }
        });
        getContentPane().add(txtfBorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 72, -1));

        Contornorgb.setForeground(new java.awt.Color(255, 255, 255));
        Contornorgb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/color-line-icono-9826-48.png"))); // NOI18N
        Contornorgb.setBorderPainted(false);
        Contornorgb.setContentAreaFilled(false);
        Contornorgb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contornorgb.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/color-line-icono-9826-32.png"))); // NOI18N
        Contornorgb.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Contornorgb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Contornorgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContornorgbActionPerformed(evt);
            }
        });
        getContentPane().add(Contornorgb, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 72, -1));
        Contornorgb.getAccessibleContext().setAccessibleName("Contornorgb");

        Relleno.setForeground(new java.awt.Color(255, 255, 255));
        Relleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pintura-de-color-icono-3767-48.png"))); // NOI18N
        Relleno.setActionCommand("Relleno");
        Relleno.setContentAreaFilled(false);
        Relleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Relleno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pintura-de-color-icono-3767-32.png"))); // NOI18N
        Relleno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Relleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoActionPerformed(evt);
            }
        });
        getContentPane().add(Relleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 72, -1));
        Relleno.getAccessibleContext().setAccessibleName("Relleno");

        txtfRelleno.setEditable(false);
        getContentPane().add(txtfRelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 72, -1));

        btnFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/AAF.jpg"))); // NOI18N
        btnFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFondoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 40, 40));

        btnImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/150361_gallery.png"))); // NOI18N
        btnImagen.setMaximumSize(new java.awt.Dimension(114, 29));
        btnImagen.setMinimumSize(new java.awt.Dimension(114, 29));
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });
        getContentPane().add(btnImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 40, 40));

        btnCurva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/0001557_32.jpg"))); // NOI18N
        btnCurva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurvaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCurva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        btnCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Image8.gif"))); // NOI18N
        btnCirculo.setMaximumSize(new java.awt.Dimension(114, 29));
        btnCirculo.setMinimumSize(new java.awt.Dimension(114, 29));
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 40, 40));

        btnTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Triangle.png"))); // NOI18N
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });
        getContentPane().add(btnTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 40, 40));

        btnRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/i31b.gif"))); // NOI18N
        btnRectangulo.setMaximumSize(new java.awt.Dimension(79, 29));
        btnRectangulo.setMinimumSize(new java.awt.Dimension(79, 29));
        btnRectangulo.setPreferredSize(new java.awt.Dimension(79, 29));
        btnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloActionPerformed(evt);
            }
        });
        getContentPane().add(btnRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, 40));

        btnLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/line_32.png"))); // NOI18N
        btnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 40));

        btnLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/10104.jpg"))); // NOI18N
        btnLapiz.setMaximumSize(new java.awt.Dimension(114, 29));
        btnLapiz.setMinimumSize(new java.awt.Dimension(114, 29));
        btnLapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapizActionPerformed(evt);
            }
        });
        getContentPane().add(btnLapiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 40));

        btnCirculoRelleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sirva-circulo-rojo-icono-8791-32.png"))); // NOI18N
        btnCirculoRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoRellenoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCirculoRelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 40, 40));

        btnRectanguloRelleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/shape_square.png"))); // NOI18N
        btnRectanguloRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloRellenoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRectanguloRelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 40));

        btnTrianguloRelleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/triangle copia.png"))); // NOI18N
        btnTrianguloRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloRellenoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrianguloRelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 40, 40));

        btnTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/text_letter_t.png"))); // NOI18N
        btnTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 40, 40));

        btnPincel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/brush-icon.png"))); // NOI18N
        btnPincel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPincelActionPerformed(evt);
            }
        });
        getContentPane().add(btnPincel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 40, 40));

        btnPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bullet_point_32x32.gif"))); // NOI18N
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 40, 40));

        btnGoma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eraser-icon.png"))); // NOI18N
        btnGoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 40));

        btnCirculoSombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/circulo_lentejuelas.png"))); // NOI18N
        btnCirculoSombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoSombraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCirculoSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 40, 40));

        btnRectanguloSombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/way3.jpg"))); // NOI18N
        btnRectanguloSombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloSombraActionPerformed(evt);
            }
        });
        getContentPane().add(btnRectanguloSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 40));

        jMenu1.setText("Archivo");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jMenu1.add(Guardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        limpiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        limpiar.setText("Limpiar pantalla");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jMenu2.add(limpiar);

        jMenu4.setText("Propiedades de Imgen");

        Translado.setText("Translado");
        Translado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransladoActionPerformed(evt);
            }
        });
        jMenu4.add(Translado);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Deshacer");

        jMenuItemDeshacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDeshacer.setText("Deshacer");
        jMenuItemDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeshacerActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemDeshacer);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        r.borrado();
    }//GEN-LAST:event_limpiarActionPerformed

    private void btnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaActionPerformed
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(11);
    }//GEN-LAST:event_btnLineaActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        r.setAccion(3);
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(4);
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnLapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapizActionPerformed
        r.setAccion(55);
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
    }//GEN-LAST:event_btnLapizActionPerformed

    private void ContornorgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContornorgbActionPerformed

        Color borde = JColorChooser.showDialog(this, "Choose a color", Color.BLACK);

        System.out.println("" + borde);
        txtfBorde.setBackground(borde);
        r.setBorde(borde);
    }//GEN-LAST:event_ContornorgbActionPerformed

    private void RellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoActionPerformed
        Color relleno = JColorChooser.showDialog(this, "Choose a color", Color.WHITE);

        System.out.println("" + relleno);
        txtfRelleno.setBackground(relleno);
        r.setRelleno(relleno);

    }//GEN-LAST:event_RellenoActionPerformed

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        r.setAccion(7);
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed

        pnlCurva.setVisible(false);
        try {
            archivos.setFileFilter(new FileNameExtensionFilter(".png/ .jpg/ .gif", "jpg", "png", "gif"));
            archivos.showOpenDialog(null);
            setXimg(archivos.getSelectedFile().getPath());
            if (ximg != null) {
                pnlImg.setVisible(true);
            }
        } catch (NullPointerException e) {
        }
    }//GEN-LAST:event_btnImagenActionPerformed

    private void btnCurvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurvaActionPerformed
        r.setAccion(8);
        pnlCurva.setVisible(true);
        pnlImg.setVisible(false);
    }//GEN-LAST:event_btnCurvaActionPerformed

    private void TransladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransladoActionPerformed
        r.setAccion(6);
    }//GEN-LAST:event_TransladoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        int width = r.getWidth(), height = r.getHeight();

        // Creamos una imagen con ese tamaño y con su correspondiente formato de
        // color
        BufferedImage imagen = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);

        // obtenemos el objeto en el que dibujar
        Graphics2D g2 = (Graphics2D) imagen.getGraphics();
        g2.setColor(Color.white);
        g2.fillRect(0, 0, width, height);

        for (Componentes f : r.getListaFiguras()) {
            if (f instanceof Imagen) {

                Imagen ima = (Imagen) f;
                ima.dibujarFigura(g2);
            }
            if (f instanceof Linea) {

                Linea l = (Linea) f;
                l.dibujarFigura(g2);
            }
            if (f instanceof Pincel) {
                Pincel pl = (Pincel) f;
                pl.dibujarFigura(g2);
            }
            if (f instanceof Goma) {
                Goma gm = (Goma) f;
                gm.dibujarFigura(g2);
            }
            if (f instanceof Texto) {
                Texto tx = (Texto) f;
                tx.dibujarFigura(g2);
            }
            if (f instanceof Triangulo) {

                Triangulo t = (Triangulo) f;
                t.dibujarFigura(g2);
            }
            if (f instanceof TrianguloRelleno) {

                TrianguloRelleno tr = (TrianguloRelleno) f;
                tr.dibujarFigura(g2);
            }
            if (f instanceof Circulo) {

                Circulo c = (Circulo) f;
                c.dibujarFigura(g2);
            }
            if (f instanceof CirculoRelleno) {
                CirculoRelleno cr = (CirculoRelleno) f;
                cr.dibujarFigura(g2);
            }
            if (f instanceof CirculoSombra) {
                CirculoSombra cs = (CirculoSombra) f;
                cs.dibujarFigura(g2);
            }
            if (f instanceof Punto) {
                Punto pt = (Punto) f;
                pt.dibujarFigura(g2);
            }
            if (f instanceof Rectangulo) {

                Rectangulo r = (Rectangulo) f;
                r.dibujarFigura(g2);
            }
            if (f instanceof RectanguloRelleno) {
                RectanguloRelleno rr = (RectanguloRelleno) f;
                rr.dibujarFigura(g2);
            }
            if (f instanceof RectanguloSombra) {
                RectanguloSombra rs = (RectanguloSombra) f;
                rs.dibujarFigura(g2);
            }
            if (f instanceof Curva) {

                Curva cu = (Curva) f;
                cu.dibujarFigura(g2);
            }
        }
        // Ejecutamos el metodo Dispose para finalizar
        g2.dispose();
        // Se crea un flujo de datos, en este caso será FileOutPutStream, aunque
        // podés utilizar cualquier otro.

        try {
            archivos.setFileFilter(new FileNameExtensionFilter(".png", "png"));
            archivos.showSaveDialog(null);
            setXimg(archivos.getSelectedFile().getPath());

            FileOutputStream out = new FileOutputStream(new File(getXimg()));

            // Se decodifica la imagen y se envía al flujo.
            //JPEGImageEncoder encoder = JPEGCodec.createJPEGEncoder(out);
//            encoder.encode(imagen);

        } catch (FileNotFoundException e) {
            // e.printStackTrace();
            //}
            //catch (ImageFormatException e) {
        } catch (IOException e) {
        } catch (NullPointerException e) {
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void txtfBordeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfBordeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBordeActionPerformed

    private void btnFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFondoActionPerformed
        // TODO add your handling code here:
        Color fondo = JColorChooser.showDialog(GarciPaintXD.this, "Elije un color", Color.WHITE);
        Lienzo.setBackground(fondo);
    }//GEN-LAST:event_btnFondoActionPerformed

    private void jMenuItemDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeshacerActionPerformed
        // TODO add your handling code here:
        r.deshacer();
    }//GEN-LAST:event_jMenuItemDeshacerActionPerformed

    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Iconos/paint_brush__s_cutiemark_by_misteraibo-d4yn3if.png"));


        return retValue;
    }
    
    
    private void btnCirculoRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoRellenoActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(14);
    }//GEN-LAST:event_btnCirculoRellenoActionPerformed

    private void btnRectanguloRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloRellenoActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(17);
    }//GEN-LAST:event_btnRectanguloRellenoActionPerformed

    private void btnTrianguloRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloRellenoActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(13);
    }//GEN-LAST:event_btnTrianguloRellenoActionPerformed

    private void LienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LienzoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_LienzoMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void btnTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextoActionPerformed
        // TODO add your handling code here:

        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(20);
        r.palabra = JOptionPane.showInputDialog("Ingrese el texto");

    }//GEN-LAST:event_btnTextoActionPerformed

    private void btnPincelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPincelActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(15);
    }//GEN-LAST:event_btnPincelActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(24);
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnGomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGomaActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(33);
    }//GEN-LAST:event_btnGomaActionPerformed

    private void btnCirculoSombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoSombraActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(80);
    }//GEN-LAST:event_btnCirculoSombraActionPerformed

    private void btnRectanguloSombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloSombraActionPerformed
        // TODO add your handling code here:
        pnlImg.setVisible(false);
        pnlCurva.setVisible(false);
        r.setAccion(90);
    }//GEN-LAST:event_btnRectanguloSombraActionPerformed

    public void gridJP() {

        pnlCurva = new JPanel(new GridLayout(3, 1, 5, 7));//filas, columnas, espacio entre filas, espacio entre columnas

        jl1 = new JLabel("Curva");
        jb1 = new JButton("Horizontal");
        jb2 = new JButton("Vertical");
        //creamos los objetos para el panel

        pnlCurva.add(jl1);
        pnlCurva.add(jb1);
        pnlCurva.add(jb2); //añadimos los objetos al jpanel

        jb1.addActionListener(this);
        jb2.addActionListener(this);

        pnlCurva.setVisible(false);
    }

    public void flowJP() {
        pnlImg = new JPanel(new GridLayout(3, 1, 5, 7));
        jt1 = new JTextField("807");
        jt2 = new JTextField("402");
        jl1 = new JLabel("Ancho");
        jl2 = new JLabel("Alto");
        jb3 = new JButton("Aceptar");//añadiendo objetos al jpanel

        /*jt1.setBounds(3, 3, 10, 10);
         jt2.setBounds(12, 13, 10, 10);
         jl1.setBounds(3, 23, 10, 10);
         jl2.setBounds(12, 33, 10, 10);
         jb3.setBounds(100, 43, 10, 10);*/
        pnlImg.add(jt1);
        pnlImg.add(jt2);
        pnlImg.add(jl1);
        pnlImg.add(jl2);
        pnlImg.add(jb3);
        jb3.addActionListener(this);

        pnlImg.setVisible(false);
    }

    public void JPfondo() {
        pnlImg = new JPanel(new GridLayout(3, 1, 5, 7));
        jt1 = new JTextField("807");
        jt2 = new JTextField("402");
        jl1 = new JLabel("Ancho");
        jl2 = new JLabel("Alto");
        jb3 = new JButton("Aceptar");//añadiendo objetos al jpanel

        /*jt1.setBounds(3, 3, 10, 10);
         jt2.setBounds(12, 13, 10, 10);
         jl1.setBounds(3, 23, 10, 10);
         jl2.setBounds(12, 33, 10, 10);
         jb3.setBounds(100, 43, 10, 10);*/
        pnlImg.add(jt1);
        pnlImg.add(jt2);
        pnlImg.add(jl1);
        pnlImg.add(jl2);
        pnlImg.add(jb3);
        jb3.addActionListener(this);

        pnlImg.setVisible(false);
    }

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GarciPaintXD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GarciPaintXD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GarciPaintXD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GarciPaintXD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GarciPaintXD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Contornorgb;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JPanel Lienzo;
    private javax.swing.JButton Relleno;
    private javax.swing.JMenuItem Translado;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCirculoRelleno;
    private javax.swing.JButton btnCirculoSombra;
    private javax.swing.JButton btnCurva;
    private javax.swing.JButton btnFondo;
    private javax.swing.JButton btnGoma;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnLapiz;
    private javax.swing.JButton btnLinea;
    private javax.swing.JButton btnPincel;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JButton btnRectanguloRelleno;
    private javax.swing.JButton btnRectanguloSombra;
    private javax.swing.JButton btnTexto;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JButton btnTrianguloRelleno;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDeshacer;
    private javax.swing.JMenuItem limpiar;
    private javax.swing.JTextField txtfBorde;
    private javax.swing.JTextField txtfRelleno;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jb1) {
            r.setV(1);
        }
        if (e.getSource() == jb2) {
            r.setV(2);
        }
        if (e.getSource() == jb3) {
            int t1 = Integer.parseInt(jt1.getText());
            int t2 = Integer.parseInt(jt2.getText());
            r.getListaFiguras().add(new Imagen(80, 40, t1, t2, null, null, getXimg()));
            pnlImg.setVisible(false);
        }

    }

    /**
     * @return the ximg
     */
    public String getXimg() {
        return ximg;
    }

    /**
     * @param ximg the ximg to set
     */
    public void setXimg(String ximg) {
        this.ximg = ximg;
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
